language: node_js
node_js: "10"

before_install:
  - cd .travis_resources

install:
  - npm install

script:
  - node test.js

after_success:
  - cd ..
  - docker build -t datascienceinstitute/gdodsiintro .

deploy:
  provider: script
  script: bash .travis_resources/docker_push.sh
  on:
    branch: master

